### ISSUE TITLE
mismatch between fc sizes and pre-trained model (256 vs 512)

### ISSUE THREAD

**Issue by lessw2020** [eraserNut/ViSha#2]
Hi - thanks very much for posting your network!
I'm trying to run some basic demo images to test it out.
After downloading the pretrained weights ("7.pth") I hit a weight size mismatch during load.  
In reviewing the TVSD code, it appears to use 256 vs these weights are trained for 512. 
Could you advise how to fix?
Here's the error in detail:
![mismatch_weighs_net_visha](https://user-images.githubusercontent.com/46302957/116139145-8c088b80-a68a-11eb-8d59-706921226904.JPG)

**Comment by eraserNut** [comment]
It is my mistake, I uploaded the old version of TVSD.py. Now, I reupload the TVSD.py again.
